DROP VIEW IF EXISTS vw_componenti_progetto_old;
DROP VIEW IF EXISTS vw_investimenti_progetto_old;
DROP VIEW IF EXISTS vw_subinvestimenti_progetto_old;
DROP VIEW IF EXISTS GMF_progettiCiclo;
DROP VIEW IF EXISTS gmf_viewEffettivo;
DROP VIEW IF EXISTS gmf_viewPrevisto;

ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgetto_sbinvestimento13;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgetto_sbinvestimento14;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgetto_sbinvestimento16;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgetto_sbinvestimento17;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgetto_sbinvestimento22;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgetto_sbinvestimento23;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_biettivospecifico;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_contribtiprevisto;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_sbinvestimento121;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_sbinvestimento123;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_sbinvestimento124;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_sbinvestimento131;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_sbinvestimento133;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_sbinvestimento225;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_sbinvestimento242;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgett_tipologiaprocedra;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgtt_inserimentstrmenti;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgtt_strttrdiriferiment;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprgtt_tiplgiprcdrffidmnt;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_asse;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_cantiere;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_clausole;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_componente1;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_componente2;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_componente3;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_componente5;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_componente6;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_fondo;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento1;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento12;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento13;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento21;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento22;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento23;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento24;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento31;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento32;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento41;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento42;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento51;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento52;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento53;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento61;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_investimento62;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_misura;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_programma;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_risorse;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub125;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub1342;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub1343;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub224;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub311;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub312;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub313;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub321;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub322;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub522;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub531;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub53es;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub611;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub621;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub622;
ALTER TABLE qckapp_g_main DROP FOREIGN KEY gmfprogetto_sub623;

DROP TABLE IF EXISTS gmfprogetto_listtag;
DROP TABLE IF EXISTS gmfprogetto_circoscrizione;
DROP TABLE IF EXISTS temp_gmf_progetti;
DROP TABLE IF EXISTS temp_gmf_input_progetti_circoscrizioni;
DROP TABLE IF EXISTS qckapp_g_main;
DROP TABLE IF EXISTS qckapp_g_tipologiadiintelce;
DROP TABLE IF EXISTS qckapp_g_statodellaprocedgq;
DROP TABLE IF EXISTS qckapp_g_inserimentoinstjxb;
DROP TABLE IF EXISTS gmftiplgiaprcedraaffidament;
DROP TABLE IF EXISTS GMF_ente;
DROP TABLE IF EXISTS GMF_utente_ente;
DROP TABLE IF EXISTS temp_gmf_configurazioni;
DROP TABLE IF EXISTS temp_gmf_input_progetti;
DROP TABLE IF EXISTS gmfmisura;
DROP TABLE IF EXISTS gmflogcarenze;
DROP TABLE IF EXISTS gmfanno1;
DROP TABLE IF EXISTS gmfprevisione;
DROP TABLE IF EXISTS gmfprevisione2021;
DROP TABLE IF EXISTS gmftagok;

DROP TABLE IF EXISTS gmfmissioni;
DROP TABLE IF EXISTS gmfcomponente1;
DROP TABLE IF EXISTS gmfcomponente2;
DROP TABLE IF EXISTS gmfcomponente3;
DROP TABLE IF EXISTS gmfcomponente4;
DROP TABLE IF EXISTS gmfcomponente5;
DROP TABLE IF EXISTS gmfcomponente6;
DROP TABLE IF EXISTS gmfinvestimento1;
DROP TABLE IF EXISTS gmfinvestimento12;
DROP TABLE IF EXISTS gmfinvestimento13;
DROP TABLE IF EXISTS gmfinvestimento21;
DROP TABLE IF EXISTS gmfinvestimento22;
DROP TABLE IF EXISTS gmfinvestimento23;
DROP TABLE IF EXISTS gmfinvestimento24;
DROP TABLE IF EXISTS gmfinvestimento31;
DROP TABLE IF EXISTS gmfinvestimento32;
DROP TABLE IF EXISTS gmfinvestimento41;
DROP TABLE IF EXISTS gmfinvestimento42;
DROP TABLE IF EXISTS gmfinvestimento51;
DROP TABLE IF EXISTS gmfinvestimento52;
DROP TABLE IF EXISTS gmfinvestimento53;
DROP TABLE IF EXISTS gmfinvestimento61;
DROP TABLE IF EXISTS gmfinvestimento62;
DROP TABLE IF EXISTS gmfsub125;
DROP TABLE IF EXISTS gmfsub1342;
DROP TABLE IF EXISTS gmfsub1343;
DROP TABLE IF EXISTS gmfsub221;
DROP TABLE IF EXISTS gmfsub224;
DROP TABLE IF EXISTS gmfsub311;
DROP TABLE IF EXISTS gmfsub312;
DROP TABLE IF EXISTS gmfsub313;
DROP TABLE IF EXISTS gmfsub321;
DROP TABLE IF EXISTS gmfsub322;
DROP TABLE IF EXISTS gmfsub521;
DROP TABLE IF EXISTS gmfsub522;
DROP TABLE IF EXISTS gmfsub531;
DROP TABLE IF EXISTS gmfsub53es;
DROP TABLE IF EXISTS gmfsub611;
DROP TABLE IF EXISTS gmfsub621;
DROP TABLE IF EXISTS gmfsub622;
DROP TABLE IF EXISTS gmfsub623;
DROP TABLE IF EXISTS gmfsubinvestimento121;
DROP TABLE IF EXISTS gmfsubinvestimento123;
DROP TABLE IF EXISTS gmfsubinvestimento124;
DROP TABLE IF EXISTS gmfsubinvestimento13;
DROP TABLE IF EXISTS gmfsubinvestimento131;
DROP TABLE IF EXISTS gmfsubinvestimento133;
DROP TABLE IF EXISTS gmfsubinvestimento14;
DROP TABLE IF EXISTS gmfsubinvestimento16;
DROP TABLE IF EXISTS gmfsubinvestimento17;
DROP TABLE IF EXISTS gmfsubinvestimento21;
DROP TABLE IF EXISTS gmfsubinvestimento22;
DROP TABLE IF EXISTS gmfsubinvestimento225;
DROP TABLE IF EXISTS gmfsubinvestimento23;
DROP TABLE IF EXISTS gmfsubinvestimento242;

DROP PROCEDURE IF EXISTS DeleteProgetto;
