CREATE TABLE `direzione_utente_ruolo` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `id_applicazione` bigint unsigned NOT NULL,
  `id_utente` bigint unsigned NOT NULL,
  `id_direzione` bigint unsigned NOT NULL,
  `id_ruolo` bigint unsigned NOT NULL,
  `flag_direzione_default` tinyint NOT NULL DEFAULT '0',
  `data_inizio_validita` datetime NOT NULL,
  `data_fine_validita` datetime DEFAULT NULL,
  `data_creazione` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `username_creazione` varchar(255) NOT NULL,
  `data_aggiornamento` datetime DEFAULT NULL,
  `username_aggiornamento` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `key_unique` (`id_applicazione`,`id_utente`,`id_direzione`,`id_ruolo`,`data_inizio_validita`),
  KEY `fk_audr_direzione` (`id_direzione`),
  KEY `fk_audr_ruolo` (`id_ruolo`),
  KEY `fk_audr_utente` (`id_utente`),
  CONSTRAINT `fk_audr_applicazione` FOREIGN KEY (`id_applicazione`) REFERENCES `applicazione` (`id_applicazione`),
  CONSTRAINT `fk_audr_direzione` FOREIGN KEY (`id_direzione`) REFERENCES `direzione` (`id_direzione`),
  CONSTRAINT `fk_audr_ruolo` FOREIGN KEY (`id_ruolo`) REFERENCES `ruolo` (`id_ruolo`),
  CONSTRAINT `fk_audr_utente` FOREIGN KEY (`id_utente`) REFERENCES `utente` (`id_utente`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
