CREATE TABLE `progetto` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `titolopropostaprogettuale` varchar(255) DEFAULT NULL,
  `oggettodelfinanziamento` varchar(255) DEFAULT NULL,
  `descrizionedelprogetto` text,
  `titolaritdelprogetto` varchar(255) DEFAULT NULL,
  `eventualialtrisoggetticoxca` varchar(255) DEFAULT NULL,
  `strutturadiriferimento` varchar(255) DEFAULT NULL,
  `fabbisognofinanziario` double DEFAULT NULL COMMENT 'Totale Accertato',
  `tipologiaproceduraattivahzy` text,
  `parerinecessari` varchar(255) DEFAULT NULL,
  `altro` varchar(255) DEFAULT NULL,
  `createdby` varchar(255) DEFAULT NULL,
  `createdon` datetime DEFAULT NULL,
  `updatedby` varchar(255) DEFAULT NULL,
  `updatedon` datetime DEFAULT NULL,
  `codice` varchar(255) DEFAULT NULL,
  `gmfasse_asse_id` int DEFAULT NULL,
  `gmffondo_fondo_id` int DEFAULT NULL,
  `gmfbttvspcfc_bttvspcific_id` int DEFAULT NULL,
  `gmfazioni_azioni_id` int DEFAULT NULL,
  `gmfprogrammi_programma_id` int DEFAULT NULL,
  `altrerisorse` double DEFAULT NULL,
  `risorseprivate` double DEFAULT NULL,
  `costototale` double DEFAULT NULL,
  `evntlfntdifinnzimentriginri` double DEFAULT NULL,
  `gmfmisura_misura_id` int DEFAULT NULL,
  `missione_id` bigint DEFAULT NULL,
  `componente_id` bigint DEFAULT NULL,
  `investimento_id` bigint DEFAULT NULL,
  `sub_investimento_id` bigint DEFAULT NULL,
  `gmftiplgia_tiplgiaperazinid` int DEFAULT NULL,
  `gmfmissioni_missione_id` int DEFAULT NULL,
  `obiettivodipolicy` varchar(255) DEFAULT NULL,
  `titolaritadelprogetto` varchar(255) DEFAULT NULL,
  `altrisoggetticoinvolti` varchar(255) DEFAULT NULL,
  `gmftplgprcdr_tiplgiprcdr_id` int DEFAULT NULL,
  `gmfstrttrdrf_strttrdrfrmn_d` int DEFAULT NULL,
  `gmfnsrmntstr_nsrmntstrmnt_d` int DEFAULT NULL,
  `direzione_id` bigint unsigned DEFAULT NULL,
  `tenant` bigint unsigned DEFAULT NULL,
  `intervento` varchar(255) DEFAULT NULL,
  `risorsestanziate` double DEFAULT NULL,
  `tiplgiaprcedradiaffidamento` varchar(255) DEFAULT NULL,
  `freemisura` varchar(255) DEFAULT NULL,
  `appaltatori` varchar(255) DEFAULT NULL,
  `subappaltatori` varchar(255) DEFAULT NULL,
  `direttorelavori` varchar(255) DEFAULT NULL,
  `gmfclausole_clausole_id` int DEFAULT NULL,
  `indirizzo` varchar(255) DEFAULT NULL,
  `comune` varchar(255) DEFAULT NULL,
  `provincia` varchar(255) DEFAULT NULL,
  `regione` varchar(255) DEFAULT NULL,
  `gmfrisorse_risorse_id` int DEFAULT NULL,
  `gmfcntrbtprvs_cntrbtprvst_d` int DEFAULT NULL,
  `gmfcantiere_cantiere_id` int DEFAULT NULL,
  `piva` varchar(255) DEFAULT NULL,
  `data_inizio_validita` datetime NOT NULL,
  `data_fine_validita` datetime DEFAULT NULL,
  `beneficiario` varchar(255) DEFAULT NULL COMMENT 'Beneficiario del progetto',
  `soggetto_attuatore_liv_II` varchar(255) DEFAULT NULL COMMENT 'Soggetto Attuatore di II livello',
  `lotto` VARCHAR(255) NULL,
  `cig`   VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  KEY `fk_gmfasse_idx` (`gmfasse_asse_id`),
  KEY `fk_gmfcantiere_idx` (`gmfcantiere_cantiere_id`),
  KEY `fk_gmfcontributoprevisto_idx` (`gmfcntrbtprvs_cntrbtprvst_d`),
  KEY `fk_gmfclausole_idx` (`gmfclausole_clausole_id`),
  KEY `fk_gmffondo_idx` (`gmffondo_fondo_id`),
  KEY `fk_gmfinserimentostrumenti_idx` (`gmfnsrmntstr_nsrmntstrmnt_d`),
  KEY `fk_obiettivospecifico_idx` (`gmfbttvspcfc_bttvspcific_id`),
  KEY `fk_gmfprogrammi_idx` (`gmfprogrammi_programma_id`),
  KEY `fk_gmfrisorse_idx` (`gmfrisorse_risorse_id`),
  KEY `fk_gmfstrutturadiriferimento_idx` (`gmfstrttrdrf_strttrdrfrmn_d`),
  KEY `fk_gmftipologiaprocedura_idx` (`gmftplgprcdr_tiplgiprcdr_id`),
  KEY `fk_gmfmissione_idx` (`missione_id`),
  KEY `fk_gmfcomponente_idx` (`componente_id`),
  KEY `fk_gmfinvestimento_idx` (`investimento_id`),
  KEY `fk_gmfsubinvestimento_idx` (`sub_investimento_id`),
  KEY `fk_tenant_idx` (`tenant`),
  KEY `fk_direzione_idx` (`direzione_id`),
  KEY `idx_ente_direzione` (`tenant`,`direzione_id`),
  KEY `idx_ente_programma` (`tenant`,`gmfprogrammi_programma_id`),
  KEY `idx_ente_fondo` (`tenant`,`gmffondo_fondo_id`),
  CONSTRAINT `fk_direzione` FOREIGN KEY (`direzione_id`) REFERENCES `direzione` (`id_direzione`),
  CONSTRAINT `fk_gmfasse` FOREIGN KEY (`gmfasse_asse_id`) REFERENCES `gmfasse` (`id`),
  CONSTRAINT `fk_gmfcantiere` FOREIGN KEY (`gmfcantiere_cantiere_id`) REFERENCES `gmfcantiere` (`id`),
  CONSTRAINT `fk_gmfclausole` FOREIGN KEY (`gmfclausole_clausole_id`) REFERENCES `gmfclausole` (`id`),
  CONSTRAINT `fk_gmfcomponente` FOREIGN KEY (`componente_id`) REFERENCES `elemento_gerarchia` (`id`),
  CONSTRAINT `fk_gmfcontributoprevisto` FOREIGN KEY (`gmfcntrbtprvs_cntrbtprvst_d`) REFERENCES `gmfcontributoprevisto` (`id`),
  CONSTRAINT `fk_gmffondo` FOREIGN KEY (`gmffondo_fondo_id`) REFERENCES `gmffondo` (`id`),
  CONSTRAINT `fk_gmfinserimentostrumenti` FOREIGN KEY (`gmfnsrmntstr_nsrmntstrmnt_d`) REFERENCES `gmfinserimentostrumenti` (`id`),
  CONSTRAINT `fk_gmfinvestimento` FOREIGN KEY (`investimento_id`) REFERENCES `elemento_gerarchia` (`id`),
  CONSTRAINT `fk_gmfmissione` FOREIGN KEY (`missione_id`) REFERENCES `elemento_gerarchia` (`id`),
  CONSTRAINT `fk_gmfobiettivospecifico` FOREIGN KEY (`gmfbttvspcfc_bttvspcific_id`) REFERENCES `gmfobiettivospecifico` (`id`),
  CONSTRAINT `fk_gmfprogrammi` FOREIGN KEY (`gmfprogrammi_programma_id`) REFERENCES `gmfprogrammi` (`id`),
  CONSTRAINT `fk_gmfrisorse` FOREIGN KEY (`gmfrisorse_risorse_id`) REFERENCES `gmfrisorse` (`id`),
  CONSTRAINT `fk_gmfstrutturadiriferimento` FOREIGN KEY (`gmfstrttrdrf_strttrdrfrmn_d`) REFERENCES `gmfstrutturadiriferimento` (`id`),
  CONSTRAINT `fk_gmfsubinvestimento` FOREIGN KEY (`sub_investimento_id`) REFERENCES `elemento_gerarchia` (`id`),
  CONSTRAINT `fk_gmftipologiaprocedura` FOREIGN KEY (`gmftplgprcdr_tiplgiprcdr_id`) REFERENCES `gmftipologiaprocedura` (`id`),
  CONSTRAINT `fk_tenant` FOREIGN KEY (`tenant`) REFERENCES `ente` (`id_ente`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `progetto` ADD COLUMN `lotto` VARCHAR(255) NULL;
ALTER TABLE `progetto` ADD COLUMN `cig`   VARCHAR(255) NULL;