INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Agrigento', 15,'AG');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Alessandria', 12,'AL');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Ancona', 10,'AN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Aosta', 19,'AO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Ascoli Piceno', 10,'AP');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('L''Aquila', 1,'AQ');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Arezzo', 16,'AR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Asti', 12,'AT');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Avellino', 4,'AV');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Bari', 13,'BA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Bergamo', 9,'BG');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Biella', 12,'BI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Belluno', 20,'BL');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Benevento', 4,'BN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Bologna', 5,'BO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Brindisi', 13,'BR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Brescia', 9,'BS');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Barletta-Andria-Trani', 13,'BT');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Bolzano', 17,'BZ');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Cagliari', 14,'CA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Campobasso', 11,'CB');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Caserta', 4,'CE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Chieti', 1,'CH');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Caltanissetta', 15,'CL');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Cuneo', 12,'CN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Como', 9,'CO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Cremona', 9,'CR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Cosenza', 3,'CS');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Catania', 15,'CT');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Catanzaro', 3,'CZ');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Enna', 15,'EN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Forlì-Cesena', 5,'FC');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Ferrara', 5,'FE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Foggia', 13,'FG');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Firenze', 16,'FI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Fermo', 10,'FM');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Frosinone', 7,'FR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Genova', 8,'GE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Gorizia', 6,'GO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Grosseto', 16,'GR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Imperia', 8,'IM');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Isernia', 11,'IS');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Crotone', 3,'KR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Lecco', 9,'LC');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Lecce', 13,'LE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Livorno', 16,'LI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Lodi', 9,'LO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Latina', 7,'LT');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Lucca', 16,'LU');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Monza e della Brianza', 9,'MB');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Macerata', 10,'MC');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Messina', 15,'ME');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Milano', 9,'MI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Mantova', 9,'MN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Modena', 5,'MO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Massa e Carrara', 16,'MS');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Matera', 2,'MT');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Napoli', 4,'NA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Novara', 12,'NO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Nuoro', 14,'NU');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Oristano', 14,'OR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Palermo', 15,'PA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Piacenza', 5,'PC');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Padova', 20,'PD');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Pescara', 1,'PE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Perugia', 18,'PG');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Pisa', 16,'PI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Pordenone', 6,'PN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Prato', 16,'PO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Parma', 5,'PR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Pistoia', 16,'PT');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Pesaro e Urbino', 10,'PU');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Pavia', 9,'PV');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Potenza', 2,'PZ');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Ravenna', 5,'RA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Reggio Calabria', 3,'RC');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Reggio Emilia', 5,'RE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Ragusa', 15,'RG');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Rieti', 7,'RI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Roma', 7,'RM');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Rimini', 5,'RN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Rovigo', 20,'RO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Salerno', 4,'SA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Siena', 16,'SI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Sondrio', 9,'SO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('La spezia', 8,'SP');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Siracusa', 15,'SR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Sassari', 14,'SS');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Sud Sardegna', 14,'SU');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Savona', 8,'SV');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Taranto', 13,'TA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Teramo', 1,'TE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Trento', 17,'TN');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Torino', 12,'TO');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Trapani', 15,'TP');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Terni', 18,'TR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Trieste', 6,'TS');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Treviso', 20,'TV');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Udine', 6,'UD');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Varese', 9,'VA');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Verbano Cusio Ossola', 12,'VB');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Vercelli', 12,'VC');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Venezia', 20,'VE');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Vicenza', 20,'VI');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Verona', 20,'VR');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Viterbo', 7,'VT');
INSERT INTO provincia (`des_provincia`, `regione_id`, `sigla_provincia`) VALUES ('Vibo Valentia', 3,'VV');
