INSERT INTO regione (`id`, `des_regione`) VALUES (1, 'Abruzzo');
INSERT INTO regione (`id`, `des_regione`) VALUES (2, 'Basilicata');
INSERT INTO regione (`id`, `des_regione`) VALUES (3, 'Calabria');
INSERT INTO regione (`id`, `des_regione`) VALUES (4, 'Campania');
INSERT INTO regione (`id`, `des_regione`) VALUES (5, 'Emilia-Romagna');
INSERT INTO regione (`id`, `des_regione`) VALUES (6, 'Friuli-Venezia Giulia');
INSERT INTO regione (`id`, `des_regione`) VALUES (7, 'Lazio');
INSERT INTO regione (`id`, `des_regione`) VALUES (8, 'Liguria');
INSERT INTO regione (`id`, `des_regione`) VALUES (9, 'Lombardia');
INSERT INTO regione (`id`, `des_regione`) VALUES (10, 'Marche');
INSERT INTO regione (`id`, `des_regione`) VALUES (11, 'Molise');
INSERT INTO regione (`id`, `des_regione`) VALUES (12, 'Piemonte');
INSERT INTO regione (`id`, `des_regione`) VALUES (13, 'Puglia');
INSERT INTO regione (`id`, `des_regione`) VALUES (14, 'Sardegna');
INSERT INTO regione (`id`, `des_regione`) VALUES (15, 'Sicilia');
INSERT INTO regione (`id`, `des_regione`) VALUES (16, 'Toscana');
INSERT INTO regione (`id`, `des_regione`) VALUES (17, 'Trentino-Alto Adige');
INSERT INTO regione (`id`, `des_regione`) VALUES (18, 'Umbria');
INSERT INTO regione (`id`, `des_regione`) VALUES (19, 'Valle d''Aosta');
INSERT INTO regione (`id`, `des_regione`) VALUES (20, 'Veneto');
